apiVersion: v1
kind: Service
metadata:
  name: reactservice-service
  labels:
    app: reactservice
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: reactservice